LongName: FIU HPC Division of Information Technology
Description: FIU Panther cluster sponsored by campus central IT division.
AddressLine1: 11200 SW 8th St
AddressLine2: PC415b
City: Miami
Country: United States
Latitude: 25.758
Longitude: -80.376
State: Florida
Zipcode: '33174'
